spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: a3292588
  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8081
logging:
  level:
    com:
      pxh: trace
    root: warn
  file:
    path: logs
  pattern:
    console: '%d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
      # 指定文件中日志输出的格式
    file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n'







